"""initial migration

Revision ID: 037f54e0f222
Revises: 
Create Date: 2025-05-28 21:27:04.945749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037f54e0f222'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailconnection',
    sa.Column('guild_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailconnection')),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_mail_connection_guild_user')
    )
    op.create_index(op.f('ix_mailconnection_token_expires_at'), 'mailconnection', ['token_expires_at'], unique=False)
    op.create_table('task',
    sa.Column('guild_id', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('importance', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='importancelevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task')),
    sa.UniqueConstraint('message_id', name=op.f('uq_task_message_id'))
    )
    op.create_index(op.f('ix_task_assigned_to'), 'task', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_task_deadline'), 'task', ['deadline'], unique=False)
    op.create_index(op.f('ix_task_guild_id'), 'task', ['guild_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_table('mailnotification',
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=False),
    sa.Column('discord_message_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['mailconnection.id'], name=op.f('fk_mailnotification_connection_id_mailconnection')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailnotification')),
    sa.UniqueConstraint('message_id', name=op.f('uq_mailnotification_message_id'))
    )
    op.create_index(op.f('ix_mailnotification_received_at'), 'mailnotification', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailnotification_received_at'), table_name='mailnotification')
    op.drop_table('mailnotification')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_guild_id'), table_name='task')
    op.drop_index(op.f('ix_task_deadline'), table_name='task')
    op.drop_index(op.f('ix_task_assigned_to'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_mailconnection_token_expires_at'), table_name='mailconnection')
    op.drop_table('mailconnection')
    # ### end Alembic commands ###
