"""add notification fields to task

Revision ID: dbf0b23e247a
Revises: 037f54e0f222
Create Date: 2024-03-20 00:03:54.467003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf0b23e247a'
down_revision: Union[str, None] = '037f54e0f222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('notification_times', sa.JSON(), nullable=True))
    op.add_column('task', sa.Column('notified_times', sa.JSON(), nullable=True))
    
    op.execute("UPDATE task SET notification_times = '[]' WHERE notification_times IS NULL")
    op.execute("UPDATE task SET notified_times = '[]' WHERE notified_times IS NULL")
    
    op.alter_column('task', 'notification_times',
                    existing_type=sa.JSON(),
                    nullable=False)
    op.alter_column('task', 'notified_times',
                    existing_type=sa.JSON(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'notified_times')
    op.drop_column('task', 'notification_times')
    # ### end Alembic commands ###
